name: Testes Automatizados Postman

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Listar arquivos para conferir o nome (DEBUG)
        run: ls -R  # <--- ESSE COMANDO VAI MOSTRAR O NOME REAL DO ARQUIVO

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Newman
        run: npm install -g newman

      - name: Rodar Testes
        # Use EXATAMENTE o nome que aparecer no log do comando "ls" acima
        run: newman run NOME_QUE_APARECEU_NO_LS.json --reporters cli
